post:
  min_box_area: 100
  aspect_ratio: 1.6

tracker:
  type: TrackTracker
  min_len: 3
  min_box_area: 100
  max_time_lost: 30
  penalty_p: 0.20
  penalty_q: 0.40
  reduce_step: 0.05
  tai_thr: 0.55
  det_thr: 0.2
  init_thr: 0.20
  match_thr: 0.70
  
detector:
  model_name: 'yolo11n.pt'
  confidence: 0.3
  iou: 0.5
  width: 1920
  height: 1080
