sim_metric: 'cosine' # choose form ['cosine', 'l2']
keep_hard: True # True for hard examples
Kmeans_with_cos_dist: True # True for using cosine similarity for kmeans clustering
emb_memory_loc: "/HDD/etc/semdedup/outputs/clip_openai/clip-vit-large-patch14-336/normed_embedding.npy"
text_emb_memory_loc: None
paths_memory_loc: "/HDD/etc/semdedup/outputs/clip_openai/clip-vit-large-patch14-336/path.npy"
sorted_clusters_file_loc: "/HDD/etc/semdedup/outputs/sorted_clusters"
save_folder: "/HDD/etc/semdedup/outputs"
path_str_dtype: "S24"
ncentroids: 2
dataset_size:  3835
emb_size: 768
niter: 100
seed: 1234
